#!/bin/bash

#(c) 2000-2015 Reciclanet Asociación Educativa-Reciclanet Hezkuntza Elkartea www.reciclanet.org
#Copyright
#Licencia GPL

#This manual is free software; you may redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2, or (at your option) any later version.

#This is distributed in the hope that it will be useful, but without any warranty; without even the implied warranty of merchantability or fitness for a particular purpose. See the GNU General Public License for more details.

#A copy of the GNU General Public License is available as /usr/share/common-licenses/GPL in the Debian GNU/Linux distribution or on the World Wide Web at the GNU website You can also obtain it by writing to the Free Software Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA

SERVER=10.10.20.3
HD='/dev/sda'
HD_SWAP=4096
HD_ROOT=20480
LOCAL_MP='/tmp/pxe'
REMOTE_MP='/pxe'
IMAGE_DIR="$LOCAL_MP/img"
NFSMOUNT=`/etc/init.d/nfsmount status | awk -F: '{print $2}' | sed 's/ //g'`
START_TIME=0
END_TIME=0

function pause(){
  read -p "$*"
}

function init_msg(){
START_TIME=`date +%s`
pause "** AUTOMATIC OS INSTALLATION **
THE CONTENTS OF THE HARD DISK WILL BE COMPLETELY ERASED.

Press CONTROL+C to cancel the installation.
Press ENTER to begin the installation."
}

function hd_format(){
echo "* Hard disk preparation *"
echo "Cleaning up MBR..."
dd if=/dev/zero of=$HD count=1 bs=512 &> /dev/null

echo 'Creating new partitions...'
echo "n
p
1

+"$HD_ROOT"M
n
p
2

+"$HD_SWAP"M
n
p
3


w" | fdisk $HD &> /dev/null

dmsetup remove_all
partprobe $HD
sleep 5

echo "Formatting new partitions..."
mkfs -t ext4 "$HD"1 &> /dev/null
NEW_SWAP_UUID=`mkswap /dev/sda2 | grep 'UUID' | cut -d "=" -f 2`
mkfs -t ext4 "$HD"3 &> /dev/null

swapon "$HD"2 &> /dev/null
echo "Finished preparing hard disk"
}

function img_install(){
echo "* Image installation *"
echo "Starting image installation"

if [ $NFSMOUNT != 'started' ]; then
    echo "NFS service is disabled, enabling..."
    /etc/init.d/nfsmount start &> /dev/null
fi

mkdir $LOCAL_MP
mount -o nolock $SERVER:$REMOTE_MP $LOCAL_MP &> /dev/null
cd $IMAGE_DIR
IMAGES=($(ls -f ./*.fsa))
cd - &> /dev/null
IMAGE_NUM=${#IMAGES[@]}
((LAST_POS=$IMAGE_NUM-1))
SELECTED=100

while ! [[ "${SELECTED}" =~ ^[0-9]+$ ]] || [ $SELECTED -lt 0 ] || [ $SELECTED -ge $IMAGE_NUM ]; do
    echo
    echo "Images available for installation:"
    for i in `seq 0 $LAST_POS`; do
        IMAGES[$i]=`echo ${IMAGES[$i]} | sed 's,./,,g'`
        echo "$i) ${IMAGES[$i]}"
    done
    echo "Please enter the number of the image that you want to install:"
    read SELECTED
    echo
done

echo "You have selected image ${IMAGES[$SELECTED]}"
echo "Starting image installation.
The operation may take around 5 minutes."

fsarchiver restfs $IMAGE_DIR/${IMAGES[$SELECTED]} id=0,dest="$HD"1 &> /dev/null
fsarchiver restfs $IMAGE_DIR/${IMAGES[$SELECTED]} id=1,dest="$HD"3 &> /dev/null
umount $IMAGE_DIR &> /dev/null

if [ $NFSMOUNT = 'started' ]; then
    echo "NFS service is enabled, disabling..."
    /etc/init.d/nfsmount start &> /dev/null
fi
}

function grub_install(){
echo "* GRUB installation *"

echo "Mounting $HD and its partitions..."
mkdir /tmp/root
mount "$HD"1 /tmp/root
mount -t proc proc /tmp/root/proc
mount -t sysfs sys /tmp/root/sys
mount -o bind /dev /tmp/root/dev

echo "Installing and configuring GRUB..."
chroot /tmp/root update-grub2 &> /dev/null
chroot /tmp/root grub-install $HD &> /dev/null

echo "Generating UUID $HD2 (swap)..."
OLD_SWAP_UUID=`cat /tmp/root/etc/fstab | grep swap | grep 'UUID' | cut -d "=" -f 2 | cut -d " " -f 1`
sed -i "s/$OLD_SWAP_UUID/$NEW_SWAP_UUID/g" /tmp/root/etc/fstab

echo "Unmounting $HD and its partitions"
umount /tmp/root/dev
umount /tmp/root/sys
umount /tmp/root/proc
umount /tmp/root
rmdir /tmp/root
}

function end_msg(){
END_TIME=`date +%s`
(( EXEC_TIME = $END_TIME - $START_TIME ))
echo "Installation finished: only rebooting the device is needed."
echo "Installation time: $EXEC_TIME seconds"
}

echo
init_msg
echo
hd_format
echo
img_install
echo
grub_install
echo
end_msg
echo
