#!/bin/bash
# (c) 2000-2018 Reciclanet Asociación Educativa-Reciclanet Hezkuntza Elkartea www.reciclanet.org
# Copyright
# Licencia GPL

# This manual is free software; you may redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2, or (at your option) any later version.

# This is distributed in the hope that it will be useful, but without any warranty; without even the implied warranty of merchantability or fitness for a particular purpose. See the GNU General Public License for more details.

# A copy of the GNU General Public License is available as /usr/share/common-licenses/GPL in the Debian GNU/Linux distribution or on the World Wide Web at the GNU website You can also obtain it by writing to the Free Software Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA

SERVER=${SERVER:-10.10.20.3}
HD=${HD:-'/dev/sda'}
HD_SWAP=${HD_SWAP:-4096}
HD_ROOT=${HD_ROOT:-20480}
LOCAL_MP=${LOCAL_MP:-'/tmp/pxe'}
REMOTE_MP=${REMOTE_MP:-'/pxe'}
IMAGE_DIR="$LOCAL_MP/${IMAGE_DIR:-img}"

START_TIME=0
END_TIME=0

function pause(){
  read -p "$*"
}

function init_msg(){
START_TIME=`date +%s`
pause "** INSTALACIÓN AUTOMÁTICA DE SSOO **
EL CONTENIDO DEL DISCO DURO SE BORRARÁ POR COMPLETO.

Pulse CONTROL+C para detener la instalación.
Pulse ENTER para comenzar la instalación."
}

function hd_format(){
echo "* Preparación del disco duro *"
echo "Limpiando MBR..."
dd if=/dev/zero of=$HD count=1 bs=512 &> /dev/null

echo 'Creando las nuevas particiones...'
echo "n
p
1

+"$HD_ROOT"M
n
p
2

+"$HD_SWAP"M
n
p
3


w" | fdisk $HD &> /dev/null

dmsetup remove_all
partprobe $HD
sleep 5

echo "Formateando las nuevas particiones..."
mkfs -t ext4 "$HD"1 &> /dev/null
NEW_SWAP_UUID=`mkswap "$HD"2 | grep 'UUID' | cut -d "=" -f 2`
mkfs -t ext4 "$HD"3 &> /dev/null

swapon "$HD"2 &> /dev/null
echo "Preparación del disco duro finalizada"
}

function img_install(){
echo "* Instalación de la imagen *"
echo "Iniciando instalación de imagen"

mkdir -p $LOCAL_MP
mount -o nolock $SERVER:$REMOTE_MP $LOCAL_MP &> /dev/null
cd $IMAGE_DIR
IMAGES=($(ls -f ./*.fsa))
cd - &> /dev/null
IMAGE_NUM=${#IMAGES[@]}
((LAST_POS=$IMAGE_NUM-1))
SELECTED=100

while ! [[ "${SELECTED}" =~ ^[0-9]+$ ]] || [ $SELECTED -lt 0 ] || [ $SELECTED -ge $IMAGE_NUM ]; do
    echo
    echo "Imagenes disponibles para su instalación:"
    for i in `seq 0 $LAST_POS`; do
        IMAGES[$i]=`echo ${IMAGES[$i]} | sed 's,./,,g'`
        echo "$i) ${IMAGES[$i]}"
    done
    echo "Introduce el número de la imagen que deseas instalar:"
    read SELECTED
    echo
done

echo "Has seleccionado la imagen ${IMAGES[$SELECTED]}"
echo "Comenzando la instalación de la imagen.
La operación puede durar aproximadamente 5 minutos."

fsarchiver restfs $IMAGE_DIR/${IMAGES[$SELECTED]} id=0,dest="$HD"1 &> /dev/null
fsarchiver restfs $IMAGE_DIR/${IMAGES[$SELECTED]} id=1,dest="$HD"3 &> /dev/null
umount $IMAGE_DIR &> /dev/null

}

function grub_install(){
echo "* Instalación de GRUB *"

echo "Montando $HD y sus particiones..."
local tmproot=$(mktemp -d)
mount "$HD"1 $tmproot
mount -t proc proc $tmproot/proc
mount -t sysfs sys $tmproot/sys
mount -o bind /dev $tmproot/dev

echo "Instalando y configurando GRUB..."
chroot $tmproot update-grub2 &> /dev/null
chroot $tmproot grub-install $HD &> /dev/null

echo "Generando UUID $HD2 (swap)..."
OLD_SWAP_UUID=`cat $tmproot/etc/fstab | grep swap | grep 'UUID' | cut -d "=" -f 2 | cut -d " " -f 1`
sed -i "s/$OLD_SWAP_UUID/$NEW_SWAP_UUID/g" $tmproot/etc/fstab

echo "Desmontando $HD y sus particiones"
umount $tmproot/dev
umount $tmproot/sys
umount $tmproot/proc
umount $tmproot
rmdir $tmproot
}

function end_msg(){
END_TIME=`date +%s`
(( EXEC_TIME = $END_TIME - $START_TIME ))
echo "Fin de la instalación: Ahora solo falta reiniciar el equio"
echo "Tiempo de instalación: $EXEC_TIME segundos"
}

echo
init_msg
echo
hd_format
echo
img_install
echo
grub_install
echo
end_msg
echo

exit 0

